name: C CI

on:
  push:
    branches:
    - workflows
    - main
  pull_request:
    branches:
    - workflows
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
